name: sample workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout actions
          uses: actions/checkout@v4s
        
        - name: welcome message  
          run: echo "my first message"
    
        - name: list 
          run: ls

        - name: read file 
          run: cat README.md

            

