name: Generating a ascii artwork 

on: push 

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo 
        uses: actions/checkout@v4

      - name: list repo files
        run: ls -ltra 

      - name: Running shell script 
        run: |
          chmod +x ./shell.sh
          ./shell.sh
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dragon_text_file
          path: ./dragon.txt

    
    needs_job:  #this job will fail because it will be running on a different runner.
        needs: ascii_job
        runs-on: ubuntu-latest
        steps:

          - name: doenload artifact 
            uses: actions/upload-artifact@v4
            with:
                name: dragon_text_file 



          - name: cat the dragon artifact file 
            run: cat dragon.txt


