name: Generating a ascii artwork 

on: 
  workflow_dispatch:   
    inputs:
      Name:
        description: "enter your name"
        required: true
        default: ":)"
        type: string
      age:
        description: "ENTER YOUR NAME"
        required: true
        type: number
      Job_role:
        description: "Chooose your job role"
        required: true
        type: choice
        options:
          - Manager
          - Developer
          - support

      Environment:
        description: "Select your role"
        required: true
        type: environment

          





jobs:
    ascii_job:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo 
        uses: actions/checkout@v4

      - name: list repo files
        run: ls -ltra 

      - name: Running shell script 
        run: |
          chmod +x ./shell.sh
          ./shell.sh
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dragon_text_file
          path: ./dragon.txt
      - name: Greeting the user
        run: |
          echo "Hi ${{github.event.inputs.Name}} Welcome"
          echo "You are ${{github.event.inputs.age}} and you are a ${{github.event.inputs.Job_role}}"

    
    needs_job:  #this job will fail because it will be running on a different runner.
        needs: ascii_job
        concurrency: 
            group: important production deployment 
            cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:

          - name: download artifact 
            uses: actions/download-artifact@v4
            with:
                name: dragon_text_file 

          - name: cat the dragon artifact file 
            run: cat dragon.txt


