name: Generating a ascii artwork 

on: push 

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo 
        uses: actions/checkout@v4

    #  - name: install cowsay program 
    #   run: sudo apt-get install cowsay -y 
          
    # - name: Execute cowsay command 
    #   run: cowsay -f dragon "Run for a cover, I asm a dragon.... Bharath" >> dragon.txt

    # - name: test file exists
    #   run: grep -i "dragon" dragon.txt

    # - name: Read created ASCII file
    #   run: cat dragon.txt

      - name: list repo files
        run: ls -ltra 

      - name: Running shell script 
        run: |
          chmod +x ./shell.sh
          ./shell.sh
    
    needs_job:  #this job will fail because it will be running on a different runner.
        needs: ascii_job
        runs-on: ubuntu-latest
        steps:
          - name: cat the shellscript 
            run: cat shell.sh


